# Note - this will not work unless you modify a few things...

# image: set this to wherever you've built your image.

# devices: this should probably be ok, but must be where you've
#          plugged your UPS into your host.

# volumes: ...

# Configuration
#  - Make sure that you've configured your apcups-mqtt.ini file correctly.
#  - .

# Using:
#  > docker-compose up --detach

# running: After this runs the first time, it will create an apcupsd.conf file
#          locally. You will probably need to modify this to work with your UPS.

version: "3"
services:
  apcups-mqtt:
    image: scooby:5000/faraday/apcups-mqtt
    container_name: apcups-mqtt
    devices:
        - /dev/usb/hiddev0
    environment:
      - TZ=Europe/London
    volumes:
      - /var/local/containers-data/apcups-mqtt/apcups-mqtt.ini:/app/apcups-mqtt.ini
      - /var/local/containers-data/apcups-mqtt/apcupsd.conf:/etc/apcupsd/apcupsd.conf
    restart: unless-stopped